name: Cache Prime Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-dependencies
          key: cache-5a16a6b

      - name: prime-cache-5a16a6b
        run: |
          echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
